// Copied unchanged from followthrough/server/lib/verify.mjs (last changed in commit 2583532, 12 Sep 2026; unchanged at HEAD 747ba94).
// The website runs the product's own deterministic checks; do not edit this file by hand.
/**
 * Deterministic verification of a targeted document edit.
 *
 * Supervisor ruling R-0041: a preservation check is a before/after comparison of
 * two things, computed in code and never asserted by a model —
 *
 *   plaintext          must differ ONLY at the targeted strings
 *   paragraph styles   must be an IDENTICAL sequence
 *
 * R-0038 is the reason this file exists. The old whole-body write reported
 * `after_contains_expected: true` while it silently flattened a HEADING_1 to
 * NORMAL_TEXT. "The text changed" was never evidence that nothing else did.
 */

/**
 * The sequence of paragraph styles in a GOOGLEDOCS_GET_DOCUMENT_BY_ID payload.
 * Non-paragraph structural elements are kept in place and labelled, so an
 * inserted table or section break shows up as a sequence difference.
 */
export function paragraphStyles(docData) {
  const doc = docData?.response_data ?? docData?.document ?? docData ?? {};
  const content = doc?.body?.content ?? [];
  return content.map((el) => {
    if (el?.paragraph) return el.paragraph.paragraphStyle?.namedStyleType ?? 'UNSTYLED';
    if (el?.table) return '[table]';
    if (el?.sectionBreak) return '[sectionBreak]';
    if (el?.tableOfContents) return '[tableOfContents]';
    return '[unknown]';
  });
}

/** Text of each paragraph, index-aligned with paragraphStyles(). */
export function paragraphTexts(docData) {
  const doc = docData?.response_data ?? docData?.document ?? docData ?? {};
  const content = doc?.body?.content ?? [];
  return content.map((el) => (el?.paragraph?.elements ?? [])
    .map((e) => e?.textRun?.content ?? '').join(''));
}

/** Line endings only. Nothing else is normalised — a lost blank line is a real loss. */
const norm = (s) => String(s ?? '').replace(/\r\n/g, '\n');

/** Case-sensitive replace-all, matching the matchCase:true we send to the API. */
export function applyReplacements(text, replacements) {
  let out = norm(text);
  for (const { find, replace } of replacements) out = out.split(find).join(replace);
  return out;
}

export const countOccurrences = (text, needle) =>
  needle ? norm(text).split(needle).length - 1 : 0;

/**
 * verifyDocEdit(before, after, replacements) -> the four values the packet asks
 * for. `before` and `after` are { text, styles } — plaintext read through
 * GET_DOCUMENT_PLAINTEXT and the style sequence read through GET_DOCUMENT_BY_ID,
 * each captured on its own side of the write.
 *
 *   dateApplied            every targeted string was swapped: the replacement is
 *                          present and the original is gone
 *   unrelatedTextPreserved after == before with exactly those swaps applied, and
 *                          nothing else — computed, not eyeballed
 *   stylesPreserved        the paragraph-style sequence is identical
 *   diffs                  every line that changed, so a human can read the delta
 */
export function verifyDocEdit(before, after, replacements = []) {
  const beforeText = norm(before?.text);
  const afterText = norm(after?.text);
  const beforeStyles = before?.styles ?? [];
  const afterStyles = after?.styles ?? [];

  /* --- did each targeted swap actually land? ---------------------------- */
  const perReplacement = replacements.map(({ find, replace }) => {
    // If the new string contains the old one, "the old string is gone" is not a
    // sound test and we say so rather than reporting a check we did not make.
    const originalCheckSound = !String(replace).includes(String(find));
    return {
      find,
      replace,
      occurrences_before: countOccurrences(beforeText, find),
      occurrences_after_of_replacement: countOccurrences(afterText, replace),
      original_absent_after: originalCheckSound ? countOccurrences(afterText, find) === 0 : null,
      original_absent_check_sound: originalCheckSound,
      applied: countOccurrences(afterText, replace) >= countOccurrences(beforeText, find)
        && countOccurrences(beforeText, find) > 0
        && (originalCheckSound ? countOccurrences(afterText, find) === 0 : true),
    };
  });
  const dateApplied = replacements.length > 0 && perReplacement.every((r) => r.applied);

  /* --- did anything ELSE move? ------------------------------------------ */
  const expected = applyReplacements(beforeText, replacements);
  const unrelatedTextPreserved = expected === afterText;

  /* --- did the paragraph-style sequence survive? ------------------------- */
  const stylesPreserved = beforeStyles.length === afterStyles.length
    && beforeStyles.every((s, i) => s === afterStyles[i]);
  const styleDiffs = [];
  for (let i = 0; i < Math.max(beforeStyles.length, afterStyles.length); i += 1) {
    if (beforeStyles[i] !== afterStyles[i]) {
      styleDiffs.push({ index: i, before: beforeStyles[i] ?? null, after: afterStyles[i] ?? null });
    }
  }

  /* --- the readable delta ------------------------------------------------ */
  const bl = beforeText.split('\n');
  const al = afterText.split('\n');
  const targeted = new Set(replacements.map((r) => r.find));
  const lineDiffs = [];
  for (let i = 0; i < Math.max(bl.length, al.length); i += 1) {
    if (bl[i] === al[i]) continue;
    lineDiffs.push({
      line: i + 1,
      before: bl[i] ?? null,
      after: al[i] ?? null,
      // A changed line is "expected" when it changed because of a targeted swap
      // and for no other reason.
      explained_by_replacement: bl[i] != null && al[i] != null
        && applyReplacements(bl[i], replacements) === al[i]
        && [...targeted].some((f) => bl[i].includes(f)),
    });
  }
  const unexplainedLineChanges = lineDiffs.filter((d) => !d.explained_by_replacement);

  return {
    dateApplied,
    unrelatedTextPreserved,
    stylesPreserved,
    diffs: {
      line_changes: lineDiffs,
      unexplained_line_changes: unexplainedLineChanges,
      unchanged_line_count: bl.filter((l, i) => l === al[i]).length,
      before_line_count: bl.length,
      after_line_count: al.length,
      style_changes: styleDiffs,
      before_styles: beforeStyles,
      after_styles: afterStyles,
      per_replacement: perReplacement,
    },
    method: 'deterministic string + paragraph-style-sequence comparison; no model involved (R-0041)',
    normalisation: 'CRLF -> LF only; blank lines and trailing whitespace are compared as-is',
  };
}

/**
 * Every excerpt a report cites must occur verbatim in the snapshot it names.
 * `getSnapshotText(source_id) -> string|null`.
 */
export function verifyExcerpts(excerpts = [], getSnapshotText) {
  const checked = excerpts.map((e) => {
    const text = getSnapshotText(e.source_id);
    const quote = String(e.quote ?? '');
    return {
      source_id: e.source_id,
      quote,
      snapshot_found: text != null,
      present_verbatim: text != null && quote.length > 0 && norm(text).includes(norm(quote)),
    };
  });
  return { all_present: checked.length > 0 && checked.every((c) => c.present_verbatim), checked };
}

/**
 * The completeness check for a continuity document — deterministic, in code.
 *
 * A document written so that a different person (or a different conversation)
 * can pick the work up has four things a machine can check without an opinion:
 * the date it describes, the time it was written, a link to every document it
 * is about, and at least one line naming something still unresolved. Whether
 * those four add up to a *useful* handover is a judgement, and judgement is the
 * Researcher's job — this function only reports what is and is not there.
 *
 * Nothing here knows what the documents are about. `links` comes from the
 * task's authorised materials, which arrive over HTTP.
 */
export function verifyContinuityDoc(text, { links = [], now = new Date() } = {}) {
  const body = String(text ?? '');
  const pad = (n) => String(n).padStart(2, '0');

  // The date, in any of the three spellings a model is likely to write it.
  const y = now.getFullYear();
  const month = now.toLocaleString('en-US', { month: 'long' });
  const shortMonth = month.slice(0, 3);
  const d = now.getDate();
  const dateForms = [
    `${y}-${pad(now.getMonth() + 1)}-${pad(d)}`,
    `${month} ${d}`, `${d} ${month}`, `${shortMonth} ${d}`, `${d} ${shortMonth}`,
  ];
  const dateMatch = dateForms.find((f) => body.toLowerCase().includes(f.toLowerCase())) ?? null;

  // A time of day: 14:05, 2:05 pm, 2 pm. Not a date fragment.
  const timeMatch = body.match(/\b([01]?\d|2[0-3]):[0-5]\d\s*(am|pm|[+-]\d{2}:?\d{2}|utc|z)?\b/i)
    ?? body.match(/\b(1[0-2]|0?\d)\s*(am|pm)\b/i);

  // Which of the documents it is about are actually linked or named by id.
  const linked = links.filter((l) => {
    const id = String(l.id ?? l);
    return id && body.includes(id);
  }).map((l) => String(l.id ?? l));

  // A line that names something still open. The wording is left free — what is
  // checked is that a line exists saying work remains.
  const outstandingLine = body.split(/\r?\n/).map((s) => s.trim()).find((line) =>
    line.length > 0
    && /\b(outstanding|not yet|awaiting|await|still needed|still open|unresolved|pending|to do|todo|next step|blocked|remains)\b/i.test(line));

  const flags = {
    containsDate: Boolean(dateMatch),
    containsTime: Boolean(timeMatch),
    linksAllPresent: links.length > 0 && linked.length === links.length,
    hasOutstandingAction: Boolean(outstandingLine),
  };
  return {
    ok: flags.containsDate && flags.containsTime && flags.linksAllPresent && flags.hasOutstandingAction,
    flags,
    matched: {
      date: dateMatch,
      time: timeMatch ? timeMatch[0] : null,
      links_found: linked,
      links_expected: links.map((l) => String(l.id ?? l)),
      links_missing: links.map((l) => String(l.id ?? l)).filter((id) => !linked.includes(id)),
      outstanding_line: outstandingLine ?? null,
    },
    chars: body.length,
  };
}
